using System;

namespace TPL.PVZR.Classes.InfoClasses
{
    [Serializable]
    public enum PlantId
    {
        NotSet = 0,
        PeaShooter = 1,
        Sunflower = 2,
        Wallnut = 3,
        Flowerpot = 4,
        SnowPea = 5,
        Marigold = 6,
        Repeater = 7,
        PotatoMine = 8,
        CherryBomb = 9,
        SplitPea = 10,
        Cactus = 11,
        TwinSunflower = 12,
        TripletSunflower = 13,
        GoldBloom = 14,
        IcebergLettuce = 15,
        Starfruit = 16,
        Threepeater = 17,
        GatlingPea = 18,
        SniperPea = 19,
        PeaPod = 20,
        Torchwood = 21,
        Tallnut = 22,
        Pumpkin = 23,
        Jalapeno = 24,
        Squash = 25,
        BonkChoy = 26,
        CabbagePult = 27,
        KernelPult = 28,
        MelonPult = 29,
        LilyPad = 30,
        PuffShroom = 31,
        SunShroom = 32,
        SeaShroom = 33,
        ScaredyShroom = 34,
        CoffeeBean = 35,
        TangleKelp = 36,
        GraveBuster = 37,
        Imitater = 38,
        Chomper = 39,
        Blover = 40,
        PeaPult = 41,
        SeasonalPult = 42,
        PepperPult = 43,
        WinterMelon = 44,
        DurianPult = 45,
        PlaceHolder_46 = 46,
        PlaceHolder_47 = 47,
        PlaceHolder_48 = 48,
        PlaceHolder_49 = 49,
        PlaceHolder_50 = 50,
        PlaceHolder_51 = 51,
        PlaceHolder_52 = 52,
        PlaceHolder_53 = 53,
        PlaceHolder_54 = 54,
        PlaceHolder_55 = 55,
        PlaceHolder_56 = 56,
        PlaceHolder_57 = 57,
        PlaceHolder_58 = 58,
        PlaceHolder_59 = 59,
        PlaceHolder_60 = 60,
        PlaceHolder_61 = 61,
        PlaceHolder_62 = 62,
        PlaceHolder_63 = 63,
        PlaceHolder_64 = 64,
        PlaceHolder_65 = 65,
        PlaceHolder_66 = 66,
        PlaceHolder_67 = 67,
        PlaceHolder_68 = 68,
        PlaceHolder_69 = 69,
        PlaceHolder_70 = 70,
        PlaceHolder_71 = 71,
        PlaceHolder_72 = 72,
        PlaceHolder_73 = 73,
        PlaceHolder_74 = 74,
        PlaceHolder_75 = 75,
        PlaceHolder_76 = 76,
        PlaceHolder_77 = 77,
        PlaceHolder_78 = 78,
        PlaceHolder_79 = 79,
        PlaceHolder_80 = 80,


        // Blover,
        // CabbagePult,
        // Caltrop,
        // CornPult,
        // MelonPult,
        // Chomper
    }
}